<?php
    include_once('../session/session.php');  
    include_once('../templates/profileHeader.php');  
    include_once('../templates/Homes/homeFunctions.php');
    include_once('../templates/reservations.php');
    include_once('../database/queries.php');
    include_once('../templates/comments.php');    
    include_once("../templates/Homes/homeFunctions.php");
    include_once("../templates/user/profile.php");
    include_once('../templates/common/Footer.php');
?>  
